import {
  ClassicEditor as ClassicEditorBase,
  Essentials,
  CKFinderUploadAdapter,
  Autoformat,
  Bold,
  Italic,
  Underline,
  BlockQuote,
  CKBox,
  CKFinder,
  EasyImage,
  Heading,
  Image,
  ImageCaption,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  PictureEditing,
  Indent,
  Link,
  List,
  MediaEmbed,
  Paragraph,
  PasteFromOffice,
  Table,
  TableToolbar,
  TextTransformation,
  CloudServices,
  SimpleUploadAdapter,
  Alignment,
  FontFamily,
  FontSize,
  FontColor,
  FontBackgroundColor,
  HorizontalLine,
  ImageResize,
  LinkImage,
} from "ckeditor5";

import "ckeditor5/ckeditor5.css";

export default class ClassicEditor extends ClassicEditorBase {
  static builtinPlugins = [
    SimpleUploadAdapter,
    Essentials,
    CKFinderUploadAdapter,
    Autoformat,
    Bold,
    Italic,
    Underline,
    BlockQuote,
    CKBox,
    CKFinder,
    CloudServices,
    EasyImage,
    Heading,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    Link,
    List,
    MediaEmbed,
    Paragraph,
    PasteFromOffice,
    PictureEditing,
    Table,
    TableToolbar,
    TextTransformation,
    Alignment,
    FontFamily,
    FontSize,
    FontColor,
    FontBackgroundColor,
    HorizontalLine,
    ImageResize,
    LinkImage,
  ];

  static defaultConfig = {
    toolbar: {
      items: [
        "undo",
        "redo",
        "|",
        "heading",
        "|",
        "alignment",
        "|",
        "fontFamily",
        "fontSize",
        "fontColor",
        "fontBackgroundColor",
        "bold",
        "italic",
        "underline",
        "|",
        "bulletedList",
        "numberedList",
        "|",
        "horizontalLine",
        "blockQuote",
        "link",
        "insertTable",
        "uploadImage",
        "mediaEmbed",
        // "outdent",
        // "indent",
      ],
    },
    link: {
      addTargetToExternalLinks: true,
    },
    mediaEmbed: {
      previewsInData: true,
    },
    image: {
      resizeOptions: [
        {
          name: "resizeImage:original",
          value: null,
          icon: "original",
        },
        {
          name: "resizeImage:50",
          value: "50",
          icon: "medium",
        },
        {
          name: "resizeImage:75",
          value: "75",
          icon: "large",
        },
      ],
      toolbar: [
        "|",
        "imageStyle:alignLeft",
        "imageStyle:alignCenter",
        "imageStyle:alignRight",
        "|",
        "resizeImage:50",
        "resizeImage:75",
        "resizeImage:original",
        "|",
        "linkImage",
      ],
      //   toolbar: [
      //     "imageStyle:inline",
      //     "imageStyle:block",
      //     "imageStyle:side",
      //     "|",
      //     "toggleImageCaption",
      //     "imageTextAlternative",
      //   ],
    },
    table: {
      contentToolbar: ["tableColumn", "tableRow", "mergeTableCells"],
    },
    language: "th",
  };
}
